// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_pelis from "./routes/api/pelis.ts";
import * as $index from "./routes/index.tsx";
import * as $peli_id_ from "./routes/peli/[id].tsx";
import * as $project from "./routes/project.tsx";
import * as $Addtoproject from "./islands/Addtoproject.tsx";
import * as $ButonIndex from "./islands/ButonIndex.tsx";
import * as $ButonModal from "./islands/ButonModal.tsx";
import * as $CreateProject from "./islands/CreateProject.tsx";
import * as $FuncionesModal from "./islands/FuncionesModal.tsx";
import * as $Listapelis from "./islands/Listapelis.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/pelis.ts": $api_pelis,
    "./routes/index.tsx": $index,
    "./routes/peli/[id].tsx": $peli_id_,
    "./routes/project.tsx": $project,
  },
  islands: {
    "./islands/Addtoproject.tsx": $Addtoproject,
    "./islands/ButonIndex.tsx": $ButonIndex,
    "./islands/ButonModal.tsx": $ButonModal,
    "./islands/CreateProject.tsx": $CreateProject,
    "./islands/FuncionesModal.tsx": $FuncionesModal,
    "./islands/Listapelis.tsx": $Listapelis,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
